---
- name: install and configure tomcat
  hosts: ubuntu
  remote_user: root
  become: yes

  vars:
    tomcat_path: "/opt/tomcat10"
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Update the System Packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Create a Tomcat User
      user:
        name: tomcat

    - name: Create a Tomcat Group
      group:
        name: tomcat

    - name: Install JAVA
      apt:
        name: openjdk-11-jdk
        state: present


    - name: Create a Tomcat Directory
      file:
        path: "{{ tomcat_path }}"
        owner: tomcat
        group: tomcat
        mode: 755
        recurse: yes

    - name: download & unarchive tomcat10
      unarchive:
        src: https://downloads.apache.org/tomcat/tomcat-9/v9.0.72//bin/apache-tomcat-9.0.72.tar.gz
        dest: /opt/tomcat10
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Change ownership of tomcat directory
      file:
        path: /opt/tomcat10
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory

    - name: Start and Enable Tomcat 10 on sever
      command: sh /opt/tomcat10/bin/startup.sh

    - name: allow tcp connections
      command: sudo ufw allow 8080/tcp