pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
        stage('Hi') {
            steps {
                echo 'Hi'
            }
        }
        stage('Good morning') {
            steps {
                echo 'Good morning'
            }
        }
    }
}
